import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { gzipSync } from 'node:zlib';
import { decodeFinanceBaseline } from '../lib/ceo-finance-baseline.mjs';
const encode=data=>gzipSync(JSON.stringify(data)).toString('base64');
const fixture={source:'Admin.xlsx',dateStart:'2024-08-01',dateEnd:'2024-11-30',months:[{month:'2024-08',income:100,expenses:20,net:80,entries:3,sources:[{name:'Mining',value:100}]}]};
const baseline=decodeFinanceBaseline(encode(fixture));
assert.equal(baseline.available,true);assert.equal(baseline.months[0].month,'sheet:2024-08');assert.equal(baseline.entries,3);
assert.equal(decodeFinanceBaseline('broken').available,false);
assert.equal(decodeFinanceBaseline(encode({...fixture,months:[fixture.months[0],fixture.months[0]]})).available,false);
assert.equal(decodeFinanceBaseline(encode({...fixture,months:[{...fixture.months[0],net:90}]})).available,false);
assert.equal(decodeFinanceBaseline(encode({...fixture,months:[{...fixture.months[0],sources:[]}]})).available,false);
const app=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const start=app.indexOf('  function renderCeoFinance(){'),end=app.indexOf('    async function adjustCeoLoyalty()',start);
const elements=new Map();const $=id=>{if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',style:{},classList:{toggle(){}}});return elements.get(id);};
const context={window:{},$,ceoFinanceData:{walletAccess:{available:false},finance:{months:[],imported:baseline},errors:[{section:'wallets'}]},ceoFinanceLoading:false,ceoCommandStatus:{connected:true},ceoSelectedMonth:'',ceoLoyaltyBusy:false,esc:String,ceoMoney:n=>n+' ISK',ceoPieStyle:()=>'valid-pie',ceoLegend:rows=>rows.map(row=>row.name).join(',')};
vm.createContext(context);vm.runInContext(app.slice(start,end),context);context.renderCeoFinance();
assert.match($('ceoIncomeSource').textContent,/ESI JOURNAL/);assert.doesNotMatch($('ceoIncomeMonth').innerHTML,/2024|sheet:/);
assert.equal($('ceoIncomeMonth').disabled,true);assert.doesNotMatch($('ceoIncomeTotals').innerHTML,/80 ISK/);
assert.match($('ceoWalletTotal').textContent,/UNAVAILABLE/,'Historical income never becomes a current wallet balance');
assert.match($('ceoOverviewMonths').textContent,/0 ESI months/);
const server=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');
const memoryStart=server.indexOf('function ceoRememberFinanceJournal('),memoryEnd=server.indexOf('function ceoFinanceSummary(',memoryStart);
const state={ceoAdmin:{financeJournal:{old:{refId:'old',date:'2020-01-01T00:00:00Z'}}}};
const memory={state};vm.createContext(memory);vm.runInContext(server.slice(memoryStart,memoryEnd),memory);
const date=new Date().toISOString();memory.ceoRememberFinanceJournal(Array.from({length:50003},(_,i)=>({ref_id:String(i),date,amount:1,_division:1})));
assert.equal(Object.keys(state.ceoAdmin.financeJournal).length,50000);assert.equal(state.ceoAdmin.financeJournal.old,undefined);
console.log('Imported finance reconciliation, live/sheet separation, missing wallet handling and journal retention passed.');
