import assert from 'node:assert/strict';
import {parseMoonSurvey,moonProduction,priceMoonProduction} from '../lib/ceo-metenox-production.mjs';
const composition=parseMoonSurvey('Product\tQuantity\tOre TypeID\nBitumens\t0.5\t45492\nCoesite\t0.5\t45493');
assert.deepEqual(composition,parseMoonSurvey('Bitumens 50%\nCoesite 50%'));
for(const text of ['Bitumens 50%','Bitumens 100%\nBitumens 1%','Bitumens -1%','Compressed Bitumens 100%','Tritanium nope','Bitumens 200%'])assert.throws(()=>parseMoonSurvey(text));
const recipes={bitumens:{moonOre:true,volume:10,portionSize:100,materials:[{typeId:16634,name:'Atmospheric Gases',quantity:1000},{typeId:34,name:'Tritanium',quantity:50000}]},coesite:{moonOre:true,volume:10,portionSize:100,materials:[{typeId:16636,name:'Silicates',quantity:2000}]}};
const production=moonProduction(composition,recipes);
assert.equal(production.error,null);
assert.deepEqual(production.outputs.map(row=>[row.name,row.perHour,row.quantity30Days]),[['Atmospheric Gases',6000,4320000],['Silicates',12000,8640000]]);
assert.equal(priceMoonProduction(production,{'Atmospheric Gases':10,Silicates:20}).revenue30Days,216000000);
assert.equal(priceMoonProduction(production,{'Atmospheric Gases':10}).revenue30Days,null,'Partial prices cannot masquerade as gross revenue');
assert.equal(priceMoonProduction(production,{'Atmospheric Gases':0,Silicates:20}).revenue30Days,null);
assert.ok(moonProduction(composition,{}).error);
assert.ok(moonProduction(composition,{...recipes,bitumens:{...recipes.bitumens,moonOre:false}}).error);
assert.ok(moonProduction([],recipes).error);
console.log('Current moon survey parsing, volume/portion/yield conversion, mineral exclusion and complete live pricing passed.');

const {default:fs}=await import('node:fs');
const {default:vm}=await import('node:vm');
const source=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');
const start=source.indexOf('async function ceoMetenoxProduction('),end=source.indexOf('let ceoStructuresCache=',start);
let requested=[];
const context={state:{ceoAdmin:{metenoxProfiles:{55:{composition},99:{composition:[{name:'Old ore',fraction:1}]}}}},moonProduction,appraisalResolveItems:async rows=>{requested=rows;return {map:new Map([['bitumens',{typeId:1,name:'Bitumens',volume:10,groupId:2396}],['coesite',{typeId:2,name:'Coesite',volume:10,groupId:2396}]])};},trackerSupport:{sdeMaterials:async()=>({available:true,items:[{typeId:1,...recipes.bitumens},{typeId:2,...recipes.coesite}]})}};
vm.createContext(context);
vm.runInContext(source.slice(start,end),context);
const drillProduction=await context.ceoMetenoxProduction([{structureId:55,typeId:81826},{structureId:99,typeId:35835}]);
assert.deepEqual(Object.keys(drillProduction),['55']);
assert.equal(drillProduction['55'].outputs[0].perHour,6000);
assert.equal(requested.length,2,'Only current drill surveys are resolved');
context.trackerSupport.sdeMaterials=async()=>({available:false,items:[]});
assert.ok((await context.ceoMetenoxProduction([{structureId:55,typeId:81826}]))['55'].error);
