import assert from 'node:assert/strict';
import fs from 'node:fs';

const server=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const ps=fs.readFileSync(new URL('../public/downloads/JLR-Tracker-Companion.ps1',import.meta.url),'utf8');
const cmd=fs.readFileSync(new URL('../public/downloads/INSTALL-JLR-TRACKER-COMPANION.cmd',import.meta.url),'utf8');

assert.match(server,/\/api\/companion\/pair\/claim/);
assert.match(server,/\/api\/companion\/location/);
assert.doesNotMatch(server,/\/api\/companion\/tracker-map/,'removed ESS/interference watch endpoint stays disabled');
assert.match(server,/source:'companion'/);
assert.match(server,/COMPANION_LOCATION_TTL_MS/);
assert.match(server,/companionTokenHash/);
assert.match(app,/COMPANION SETUP/,'Adam keeps the companion setup controls');
assert.match(app,/brainCompanionFeedTrack/,'Brain shows a live companion movement feed');
assert.match(app,/locationSource==='companion'/,'Auto Follow labels companion-fed locations');
assert.match(server,/companionLocationsForUser/,'companion status exposes fresh toon locations');
assert.match(server,/companionDeviceName/,'companion location cache keeps the paired device name');
assert.match(server,/function companionActiveForUser/,'paired companion health is tracked at account level');
assert.match(server,/COMPANION_WAITING/,'healthy companion suppresses ESI location fallback');
assert.match(app,/WAITING FOR COMPANION/,'Auto Follow shows companion wait state instead of an ESI error');
assert.match(app,/EVE LOCATION CHECKS ACTIVE/,'Adam shows when ESI location checks are active');
assert.match(app,/NOISE_SUPPRESS/);
assert.match(ps,/Encoding\]::Unicode/,'EVE chat logs are read as UTF-16LE/Unicode');
assert.match(ps,/Channel changed to Local/);
assert.match(ps,/Listener:/);
assert.match(ps,/\/api\/companion\/location/);
assert.match(ps,/ConvertFrom-SecureString/,'pair token is protected with Windows DPAPI through SecureString');
assert.match(ps,/SecureStringToBSTR/,'protected pair token can be restored for API calls');
assert.match(ps,/LastSentAt/,'companion heartbeats unchanged locations');
assert.match(ps,/TotalSeconds -ge 30/,'companion heartbeat interval is 30 seconds');
assert.match(cmd,/JLR-Tracker-Companion\.ps1/);
console.log('Desktop companion integration tests passed.');
