import assert from 'node:assert/strict';
import fs from 'node:fs';

const server=fs.readFileSync(new URL('../server.mjs',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const ps=fs.readFileSync(new URL('../public/downloads/JLR-Tracker-Companion.ps1',import.meta.url),'utf8');
const cmd=fs.readFileSync(new URL('../public/downloads/INSTALL-JLR-TRACKER-COMPANION.cmd',import.meta.url),'utf8');

assert.match(server,/\/api\/companion\/pair\/claim/);
assert.match(server,/\/api\/companion\/location/);
assert.match(server,/\/api\/companion\/scan/,'approved companion can submit observed Probe Scanner text');
assert.match(server,/COMPANION_OBSERVER_NAMES/,'trusted screen observers are configured separately from admin access');
assert.match(server,/companionObserverAccess\(auth\.user\)/,'observer endpoint accepts only owner or trusted screen observers');
assert.match(server,/OBSERVER_NOT_ALLOWED/,'observer endpoint rejects unapproved accounts');
assert.match(server,/OBSERVER_SYSTEM_CHANGED/,'observer rejects a frame after the toon changes systems');
assert.doesNotMatch(server,/\/api\/companion\/tracker-map/,'removed ESS/interference watch endpoint stays disabled');
assert.match(server,/source:'companion'/);
assert.match(server,/COMPANION_LOCATION_TTL_MS/);
assert.match(server,/companionTokenHash/);
assert.match(app,/COMPANION SETUP/,'Adam keeps the companion setup controls');
assert.match(app,/brainCompanionFeedTrack/,'Brain shows a live companion movement feed');
assert.match(app,/locationSource==='companion'/,'Auto Follow labels companion-fed locations');
assert.match(server,/companionLocationsForUser/,'companion status exposes fresh toon locations');
assert.match(server,/companionDeviceName/,'companion location cache keeps the paired device name');
assert.match(server,/function companionActiveForUser/,'paired companion health is tracked at account level');
assert.match(server,/COMPANION_WAITING/,'healthy companion suppresses ESI location fallback');
assert.match(app,/WAITING FOR COMPANION/,'Auto Follow shows companion wait state instead of an ESI error');
assert.match(app,/EVE LOCATION CHECKS ACTIVE/,'Adam shows when ESI location checks are active');
assert.match(ps,/Encoding\]::Unicode/,'EVE chat logs are read as UTF-16LE/Unicode');
assert.match(ps,/Channel changed to Local/);
assert.match(ps,/Listener:/);
assert.match(ps,/\/api\/companion\/location/);
assert.match(ps,/Windows\.Media\.Ocr\.OcrEngine/,'observer uses Windows built-in OCR');
assert.match(ps,/GetForegroundWindow/,'observer can safely identify the foreground EVE client for fallback and clipboard gating');
assert.match(ps,/Get-JlrObserverEveIdentity/,'screen observer locks to the configured EVE character window');
assert.match(ps,/PrintWindow/,'screen observer captures the selected EVE client without requiring foreground focus');
assert.match(ps,/\/api\/companion\/scan/,'observer submits recognized scanner text through companion auth');
assert.match(ps,/GetClipboardSequenceNumber/,'companion watches clipboard changes without polling clipboard contents blindly');
assert.match(ps,/Creator Scan Mode:/,'companion exposes creator scan modes in the tray');
assert.match(ps,/COPY AUTO-IMPORT/,'creator can choose clipboard-only scanning');
assert.match(ps,/SCREEN WATCH/,'creator can choose passive screen OCR');
assert.match(ps,/HYBRID \(COPY \+ SCREEN\)/,'creator can run clipboard and screen watch together');
assert.match(ps,/Yeda Parmala/,'owner screen watch keeps the creator scouting toon default');
assert.match(ps,/observerCharacterName/,'delegated observer pairing can target its approved EVE toon automatically');
assert.match(ps,/approved JLR observer accounts/i,'screen-watch UI explains the delegated observer gate');
assert.match(ps,/observerCharacter/,'screen watch can be targeted to a chosen EVE toon');
assert.match(ps,/\/api\/companion\/clipboard/,'EVE clipboard copies are sent through companion auth');
assert.match(ps,/Get-JlrForegroundEveIdentity/,'clipboard imports are gated to the foreground EVE client');
assert.match(server,/\/api\/companion\/clipboard/,'server accepts paired clipboard imports');
assert.match(server,/\/api\/companion\/clipboard\/stream/,'browser gets user-scoped clipboard events');
assert.match(server,/classifyCompanionClipboard/,'server routes ore, probe, and threat clipboard formats');
assert.match(app,/connectCompanionClipboardStream/,'tracker listens for companion clipboard events');
assert.match(app,/clipboard-ore-survey/,'ore survey clipboard events populate Adam context');
assert.match(app,/clipboard-threat-scan/,'Local and D-scan clipboard events populate Threat Scan');
assert.match(app,/clipboard-probe-scan/,'Probe Scanner clipboard events populate scan state');
assert.doesNotMatch(ps,/SendKeys|mouse_event/i,'observer never automates EVE input');
assert.match(ps,/ConvertFrom-SecureString/,'pair token is protected with Windows DPAPI through SecureString');
assert.match(ps,/SecureStringToBSTR/,'protected pair token can be restored for API calls');
assert.match(ps,/LastSentAt/,'companion heartbeats unchanged locations');
assert.match(ps,/TotalSeconds -ge 30/,'companion heartbeat interval is 30 seconds');
assert.match(ps,/TotalHours -lt 1/,'screen observer sends at most one successful scan per system per hour');
assert.match(cmd,/JLR-Tracker-Companion\.ps1/);
console.log('Desktop companion integration tests passed.');
