import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
let at = 1000, sounds = 0, animations = 0;
const window = { matchMedia: () => ({ matches: false }) };
vm.runInNewContext(fs.readFileSync(new URL('../public/field-update-feedback.js', import.meta.url), 'utf8'), { window, Date: { now: () => at } });
const feedback = window.JlrFieldUpdateFeedback;
const cards = ['A', 'B'].map(system => ({ dataset: { system, status: 'ready' }, classList: { contains: () => false }, animate: () => { animations++; return {}; } }));
const board = { querySelectorAll: () => cards };
const notify = () => sounds++;
const state = { fields: { A: { updatedAt: 'old' }, B: { updatedAt: 'old' } } };
feedback.observe(state); feedback.paint(board, notify);
assert.equal(sounds, 0, 'no chime on initial load');
state.fields.A.updatedAt = state.fields.B.updatedAt = 'new';
feedback.observe(state); feedback.paint(board, notify);
assert.equal(sounds, 1, 'one subtle chime for a batch of visible updates');
assert.equal(animations, 2);
feedback.paint(board, notify);
assert.equal(sounds, 1, 'rendering an existing blink never repeats its chime');
at += 100;
state.fields.A.updatedAt = 'newer';
feedback.observe(state); feedback.paint(board, notify);
assert.equal(sounds, 2);
at += 2500;
feedback.observe(state); feedback.paint(board, notify);
assert.equal(sounds, 2, 'expired feedback is silent');
window.matchMedia = () => ({ matches: true });
const before = animations;
state.fields.A.updatedAt = 'latest';
feedback.observe(state); feedback.paint(board, notify);
assert.equal(animations, before, 'reduced motion suppresses the animation');
assert.equal(sounds, 3, 'sound remains independently controlled');
const app = fs.readFileSync(new URL('../public/app.js', import.meta.url), 'utf8');
assert.match(app, /if\(!soundEnabled\)return false/);
assert.match(app, /if\(!document.hidden\)sfx\('fieldUpdate'\)/);
const server = fs.readFileSync(new URL('../server.mjs', import.meta.url), 'utf8');
const scout = server.slice(server.indexOf("url.pathname==='/api/scout/targets'"), server.indexOf("url.pathname==='/api/tracker/brain/ask'"));
assert.match(scout, /nearestScan:targets\[0\]\|\|null/);
assert.doesNotMatch(scout, /updatesOnly:false/);
console.log('Field feedback chime batching, deduplication, expiry, motion and nearest-scan defaults passed.');
