import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
let at = 1000, sounds = 0, animations = 0;
const window = { matchMedia: () => ({ matches: false }) };
vm.runInNewContext(fs.readFileSync(new URL('../public/field-update-feedback.js', import.meta.url), 'utf8'), { window, Date: { now: () => at } });
const feedback = window.JlrFieldUpdateFeedback;
const cards = ['A', 'B'].map(system => ({ dataset: { system, status: 'ready' }, classList: { contains: () => false }, animate: () => { animations++; return {}; } }));
const board = { querySelectorAll: () => cards };
const notify = () => sounds++;
const state = { fields: { A: { updatedAt: 'old' }, B: { updatedAt: 'old' } } };
feedback.observe(state); feedback.paint(board, notify);
assert.equal(sounds, 0, 'no chime on initial load');
state.fields.A.updatedAt = state.fields.B.updatedAt = 'new';
feedback.observe(state); feedback.paint(board, notify);
assert.equal(sounds, 1, 'one subtle chime for a batch of visible updates');
assert.equal(animations, 2);
feedback.paint(board, notify);
assert.equal(sounds, 1, 'rendering an existing blink never repeats its chime');
assert.equal(animations,2,'rendering does not stack duplicate animations');
at += 100;
state.fields.A.updatedAt = 'newer';
feedback.observe(state); feedback.paint(board, notify);
assert.equal(sounds, 2);
at += 2500;
feedback.observe(state); feedback.paint(board, notify);
assert.equal(sounds, 2, 'expired feedback is silent');
window.matchMedia = () => ({ matches: true });
const before = animations;
state.fields.A.updatedAt = 'latest';
feedback.observe(state); feedback.paint(board, notify);
assert.equal(animations, before, 'reduced motion suppresses the animation');
assert.equal(sounds, 3, 'sound remains independently controlled');
// Grouped T2 arrays use map:t2|SYSTEM, not the unrelated T3 identity.
window.matchMedia=()=>({matches:false});
let t2Animations=0,t2Cancelled=0,t3Animations=0;
const t2={dataset:{system:'A',boardKey:'map:t2|A',status:'map'},classList:{contains:name=>name==='map-field-node'},animate:(_frames,options)=>{assert.equal(options.duration*options.iterations,15000);t2Animations++;return {cancel(){t2Cancelled++}}}};
const t3={dataset:{system:'A',boardKey:'t3:A',status:'ready'},classList:{contains:()=>false},animate:()=>{t3Animations++;return {}}};
const t2Board={querySelectorAll:()=>[t2,t3]};
state.source={mapFields:[{id:'one',tier:2,system:'A',ore:'Bistot',status:'ready',minedM3:0},{id:'two',tier:2,system:'A',ore:'Arkonor',status:'ready',minedM3:0}]};
feedback.observe(state);at+=15001;feedback.observe(state);feedback.paint(t2Board,notify);
const beforeSound=sounds;
state.scans={A:{lastScanAt:'new T2 scan'}};
feedback.observe(state);feedback.paint(t2Board,notify);
assert.equal(t2Animations,1,'a scanner update blinks the grouped T2 card');
assert.equal(sounds,beforeSound+1,'one chime for the update batch');
for(let n=0;n<14;n++){at+=1000;feedback.observe(state);feedback.paint(t2Board,notify);}
assert.equal(t2Animations,1,'one animation continues for the full 15 seconds');
assert.equal(t2Cancelled,0,'still running at 14 seconds');
at+=1000;feedback.observe(state);feedback.paint(t2Board,notify);
assert.equal(t2Cancelled,1,'blink ends at exactly 15 seconds');
const t3Before=t3Animations;
state.source.mapFields[1].minedM3=250;
feedback.observe(state);feedback.paint(t2Board,notify);
assert.equal(t2Animations,2,'a mineral update refreshes the grouped T2 card');
assert.equal(t3Animations,t3Before,'T2-only updates do not blink the T3 card');
state.source.mapFields.reverse();feedback.observe(state);feedback.paint(t2Board,notify);
assert.equal(t2Animations,2,'row order alone is not an update');
at+=1000;state.source.mapFields[0].status='cleared';feedback.observe(state);feedback.paint(t2Board,notify);
assert.equal(t2Animations,3,'new field status starts a new 15-second indication');
state.fieldAccess={allowed:false};feedback.observe(state);feedback.paint(t2Board,notify);
assert.equal(t2Cancelled,3,'access revocation cancels pending feedback');
const app = fs.readFileSync(new URL('../public/app.js', import.meta.url), 'utf8');
assert.match(app, /if\(!soundEnabled\)return false/);
assert.match(app, /if\(!document.hidden\)sfx\('fieldUpdate'\)/);
const server = fs.readFileSync(new URL('../server.mjs', import.meta.url), 'utf8');
const scout = server.slice(server.indexOf("url.pathname==='/api/scout/targets'"), server.indexOf("url.pathname==='/api/tracker/brain/ask'"));
assert.match(scout, /nearestScan:targets\[0\]\|\|null/);
assert.doesNotMatch(scout, /updatesOnly:false/);
console.log('Field feedback chime batching, deduplication, expiry, motion and nearest-scan defaults passed.');
