import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const ctx=vm.createContext({window:{}});
vm.runInContext(readFileSync(new URL('../public/field-status.js',import.meta.url),'utf8'),ctx);
const build=ctx.window.JlrFieldStatus.build,now=Date.parse('2026-10-05T20:00:00Z');
const at=delta=>new Date(now+delta).toISOString();
const fixture=()=>({state:{fieldAccess:{allowed:true},scans:{A:{lastScanAt:at(-60000)}},miningActivity:{},playerLosses:{}},entry:{key:'t3:A',kind:'t3',system:'A',d:{ore:'Bistot'},f:{status:'ready'}},systemEntryCount:2,scanHint:{stale:false}});
const value=(s,label)=>build(s,now).details.find(([name])=>name===label)?.[1];
let s=fixture();
s.state.miningActivity.A=at(-1000);
assert.match(value(s,'Mining'),/No recent/,'ambiguous system activity must not light up every field');
s.state.miningActivity['ice:A']=at(-1000);
assert.match(value(s,'Mining'),/No recent/);
s.state.miningActivity['t3:A']=at(-1000);
assert.match(value(s,'Mining'),/Recent field-matched/);
assert.match(value(s,'Miners present'),/Unknown/);
s.state.playerLosses.A={at:at(-1000)};
assert.match(value(s,'Mining'),/loss reported/);
assert.equal(build(s,now).activity[0].alert,true);
assert.match(build(s,now).activity[0].text,/in this system/);
assert.match(build(s,now+46*60000).details.find(([n])=>n==='Mining')[1],/No recent/);
s.entry.f={status:'cleared',timerEndsAt:at(1000)};
assert.match(value(s,'Reset'),/00:00:01/);
assert.match(build(s,now+2000).details.find(([n])=>n==='Reset')[1],/scan to confirm/);
s.state.scans.A.ledger={siteM3:100,verifiedM3SinceScan:25,baselineDetected:true,baselineAt:at(-60000),verifiedFromScanAt:at(-60000)};
assert.match(value(s,'Reported progress'),/25%/);
s.state.scans.A.ledger.verifiedFromScanAt=null;
assert.match(value(s,'Progress'),/Awaiting/);
s.state.scans.A.source='clear-report';assert.ok(value(s,'Last clear report'));
s=fixture();s.entry={key:'map:t2|A',kind:'map',system:'A',row:{tier:2,rows:[{ore:'Bistot',status:'cleared',timerEndsAt:at(2000),siteM3:100,minedM3:100},{ore:'Arkonor',status:'picked',siteM3:200,minedM3:20}]}};
assert.equal(value(s,'Field state'),'Partially cleared');assert.match(value(s,'Bistot progress'),/100 m³/);assert.match(value(s,'Arkonor progress'),/20 m³/);
s=fixture();s.entry={key:'ice:A',kind:'ice',system:'A',row:{iceBelts:2}};
assert.equal(value(s,'Field state'),'Unconfirmed');
s.state.scans.A.ice={seen:1};assert.equal(value(s,'Field state'),'1 up · 1 down / cleared');
s=fixture();s.entry={key:'a0:A',kind:'a0',system:'A',row:{scan:{detected:true,lastCheckedAt:at(-60000)}}};
assert.equal(value(s,'Field state'),'Site active');s.entry.row.scan.superseded=true;assert.equal(value(s,'Field state'),'Previous site');
s.state.fieldAccess.allowed=false;assert.equal(build(s,now),null);
s=fixture();s.entry=null;assert.equal(build(s,now),null);
console.log('Field status: exact-card mining, unknown presence, losses, reset expiry, verified progress, grouped T2, ice, A0 and access revocation passed.');
