import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {recordPlayerLoss,prunePlayerLosses,playerLossSnapshot,PLAYER_LOSS_WINDOW_MS} from '../lib/field-player-loss.mjs';
import {redactFieldState} from '../lib/init-field-access.mjs';
const at=Date.parse('2026-10-05T12:00:00Z'),store={};
const kill=(id,systemId,age)=>({killmail_id:id,solar_system_id:systemId,killmail_time:new Date(at-age).toISOString(),victim:{character_id:99,ship_type_id:17478}});
assert.equal(recordPlayerLoss(store,kill(1,10,1000),at),true);
assert.equal(recordPlayerLoss(store,kill(1,10,1000),at),false,'duplicates do not extend the warning');
assert.equal(recordPlayerLoss(store,kill(2,10,2000),at),false,'out-of-order arrivals do not replace a newer loss');
assert.equal(recordPlayerLoss(store,kill(3,20,PLAYER_LOSS_WINDOW_MS-1),at),true);
assert.equal(recordPlayerLoss(store,kill(4,30,PLAYER_LOSS_WINDOW_MS),at),false,'exact cutoff excluded');
assert.equal(recordPlayerLoss(store,kill(5,40,-1),at),false,'future events excluded');
assert.equal(recordPlayerLoss(store,{...kill(6,50,100),victim:{ship_type_id:17478}},at),false,'NPC victims excluded');
assert.equal(recordPlayerLoss(store,{...kill(7,50,100),killmail_time:'bad'},at),false);
assert.deepEqual(Object.keys(playerLossSnapshot(store,new Map([['A',10],['B',20],['C',30]]),at)),['A','B']);
prunePlayerLosses(store,at+1);assert.equal(store[20],undefined,'systems expire independently');
assert.deepEqual(redactFieldState({playerLosses:{A:store[10]},source:{}},{allowed:false}).playerLosses,{});
const window={},document={addEventListener(){},querySelectorAll(){return []}};
vm.runInNewContext(fs.readFileSync(new URL('../public/field-player-loss.js',import.meta.url),'utf8'),{window,document,performance:{now:()=>0}});
assert.equal(window.JlrFieldPlayerLoss.recent(store[10],at),true);
assert.equal(window.JlrFieldPlayerLoss.recent(store[10],Date.parse(store[10].at)+PLAYER_LOSS_WINDOW_MS),false);
assert.equal(window.JlrFieldPlayerLoss.recent(store[10],at-2000),false);
console.log('Player-loss qualification, duplicate/out-of-order handling, per-system 30-minute expiry, redaction and browser cutoff passed.');
