import assert from 'node:assert/strict';
import fs from 'node:fs';

const index=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const styles=fs.readFileSync(new URL('../public/styles.css',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const tracker=fs.readFileSync(new URL('../public/tracker-core.js',import.meta.url),'utf8');
const trackerCss=fs.readFileSync(new URL('../public/tracker.css',import.meta.url),'utf8');
const trackerLoader=fs.readFileSync(new URL('../public/tracker.js',import.meta.url),'utf8');
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));

assert.match(index,/class="kpis information-kpis operations-summary-bar"/,'top metrics are presented as one summary bar');
assert.match(index,/class="kpi summary-cell summary-cell-payout api-kpi app-payout-kpi"/,'app payout leads the one-line summary');
assert.match(index,/class="kpi summary-cell fleet-target-kpi"/,'fleet target remains a compact summary metric');
assert.match(index,/>MY TOONS<\/span>/,'personal payout stays in the top summary');
assert.match(index,/>JITA \/ HR<\/span>[\s\S]*>C-N \/ HR<\/span>/,'Jita and C-N remain adjacent in the summary flow');
assert.match(styles,/v2\.9\.144 — one-line decision summary/,'top summary uses the one-line decision bar');
assert.match(styles,/\.operations-summary-bar\{display:grid;grid-template-columns:/,'all six summary metrics share one horizontal grid');
assert.match(styles,/repeat\(6,minmax\(105px,1fr\)\)/,'summary compresses evenly before mobile overflow');
assert.doesNotMatch(index,/market-payout-pair/,'summary no longer needs a nested market row');
assert.match(index,/appLedgerCoverageBadge/,'app ledger coverage is a compact badge');
assert.match(index,/myLedgerCoverageBadge/,'personal ledger coverage is a compact badge');
assert.match(index,/data-nav-group="ops"[\s\S]*?<strong>OPS<\/strong>/,'navigation has an Operations group');
assert.match(index,/data-nav-group="resources"[\s\S]*?<strong>RESOURCES<\/strong>/,'navigation has a Resources group');
assert.match(index,/data-nav-group="intel"[\s\S]*?<strong>INTEL<\/strong>/,'navigation has an Intel group');
assert.match(index,/data-nav-group="system"[\s\S]*?<strong>SYSTEM<\/strong>/,'navigation has a System group');
assert.match(index,/id="donateTop"/,'global Donate control is present in the app header');
assert.match(index,/paypal\.com\/ncp\/payment\/J7UYHR2RJFS6N/,'global Donate control uses the configured PayPal destination');
assert.match(app,/jlr-donate-banner-feedback/,'Feedback hub contains the full Donate banner');
assert.match(styles,/\.jlr-donate-banner\{--donate-accent:var\(--theme-accent/,'Donate banner inherits the active dashboard theme');
assert.match(styles,/\.donate-top-link/,'global Donate control has a compact themed treatment');
assert.match(index,/value="neon"[^>]*>NEON GRID<\/option>/,'Neon Grid theme is available');
assert.match(index,/value="glacier"[^>]*>GLACIER<\/option>/,'Glacier theme is available');
assert.match(index,/value="solar"[^>]*>SOLAR FLARE<\/option>/,'Solar Flare theme is available');
assert.match(index,/value="industrial"[^>]*>INDUSTRIAL<\/option>/,'legacy Forge theme is renamed Industrial');
assert.match(styles,/\.nav-menu\[open\]\{z-index:120\}/,'open dropdown is raised above neighboring nav groups');
assert.match(index,/id="themeSelectIcon"/,'theme selector shows the selected EVE image');
assert.match(index,/data-theme-icon="neon"/,'theme choices use original JLR glyph identifiers');
assert.match(styles,/\.theme-menu-image/,'theme picker renders original glyph thumbnails');
assert.match(styles,/html\[data-theme="neon"\] body::before/,'Neon Grid has its own animated grid treatment');
assert.match(styles,/html\[data-theme="glacier"\] \.glass/,'Glacier has frosted glass surfaces');
assert.match(styles,/html\[data-theme="solar"\] body::before/,'Solar Flare has its own radiant treatment');
assert.match(styles,/html\[data-theme="industrial"\] body::after/,'Industrial has hazard-rail styling');
assert.match(app,/function themeIconMarkup/,'theme selector glyphs are generated locally');
assert.doesNotMatch(index,/images\.evetech\.net\/types\//,'theme selector no longer depends on EVE ship or ore art');
assert.match(styles,/gothic cathedral \/ ritual terminal/,'Blood has a dark gothic identity');
assert.match(styles,/white-hot star \/ orbital heat shield/,'Solar Flare has a bright stellar identity');
assert.match(styles,/jlr-solar-rays/,'Solar Flare has rotating corona rays distinct from Blood');
assert.match(styles,/event-horizon observatory/,'Void has event-horizon personality');
assert.match(styles,/armored bulkheads and structural brackets/,'Citadel has armored structural personality');
assert.match(styles,/bolted machinery and warning rails/,'Industrial has bolted machinery personality');
assert.match(styles,/active bio-scanner/,'Serpentis has live scanner personality');
assert.match(styles,/analog flight-deck \/ worn brass instrumentation/,'Angel has analog flight-deck personality');
assert.match(styles,/tactical radar and target brackets/,'EDENCOM has tactical radar personality');
assert.match(styles,/floating luminous glass, soft motion/,'Aurora has floating-glass personality');
assert.match(styles,/active HUD scanline and reactive modules/,'Neon has reactive HUD personality');
assert.match(styles,/fractured crystal facets rather than HUD cuts/,'Glacier has fractured-crystal personality');
assert.match(styles,/orbital rings and radiant instrumentation/,'Solar has orbital instrumentation personality');
assert.match(styles,/FINAL THEME ART DIRECTION/,'final art-direction layer is present');
assert.match(styles,/VOID — event horizon \/ silent deep-space observatory/,'Void final identity is present');
assert.match(styles,/CITADEL — armored station bulkhead \/ command bridge/,'Citadel final identity is present');
assert.match(styles,/INDUSTRIAL — heavy machinery \/ service bay/,'Industrial final identity is present');
assert.match(styles,/SERPENTIS — biotech scan console/,'Serpentis final identity is present');
assert.match(styles,/BLOOD — ritual cathedral \/ reliquary/,'Blood final identity is present');
assert.match(styles,/ANGEL — rugged retro flight deck \/ analog avionics/,'Angel final identity is present');
assert.match(styles,/EDENCOM — clean military tactical display/,'EDENCOM final identity is present');
assert.match(styles,/AURORA — floating liquid glass \/ luminous atmosphere/,'Aurora final identity is present');
assert.match(styles,/NEON GRID — aggressive cyberpunk HUD/,'Neon final identity is present');
assert.match(styles,/GLACIER — faceted ice crystal \/ frozen observatory/,'Glacier final identity is present');
assert.match(styles,/SOLAR FLARE — heliostat \/ orbital solar instrumentation/,'Solar final identity is present');
assert.match(styles,/jlr-glyph-solar/,'selected theme glyphs have theme-specific behavior');
assert.match(styles,/THEME QA CONSISTENCY PASS/,'theme QA consistency layer is present');
assert.match(styles,/\.orb\.active\{\s*outline-color:var\(--theme-accent-hi/,'active controls no longer leak hard-coded purple');
assert.match(styles,/\.system-node\.selected\{\s*outline-color:var\(--theme-accent-hi/,'selected field outline follows the active theme');
assert.match(styles,/INDUSTRIAL — stamped service-bay material/,'Industrial has a dedicated QA material pass');
assert.match(styles,/quiet orbital glow/,'Void status colors preserve its material');
assert.match(styles,/armored status rail/,'Citadel status colors preserve its material');
assert.match(styles,/status becomes bioluminescence/,'Serpentis status colors preserve its material');
assert.match(styles,/status softly refracts through the glass/,'Aurora status colors preserve its material');
assert.match(styles,/semantic status is a third signal channel/,'Neon status colors preserve its material');
assert.match(styles,/state color becomes a refracted facet edge/,'Glacier status colors preserve its material');
assert.match(styles,/semantic state appears as an instrument ring/,'Solar status colors preserve its material');

assert.match(index,/id="fleetInsight"/,'Fleet Performance has a decision-first live insight');
assert.match(app,/Sampled rate met the fitted target/,'Fleet insight interprets sampled rate versus target');
assert.match(app,/fleetInsightMeter/,'Fleet insight uses a compact target-comparison meter');
assert.match(styles,/\.fleet-insight-meter/,'Fleet insight meter is styled');

assert.doesNotMatch(app,/class="ore-mix-bar"/,'Ore Mix no longer uses ambiguous top-relative bars');
assert.match(app,/ore-mix-composition/,'Ore Mix uses one proportional composition strip');
assert.match(styles,/\.ore-mix-compact-list/,'Ore Mix keeps exact values in a compact list');

assert.match(tracker,/const topMetric=top\?trackerIntelMetric/,'Hot Zones only promotes a top signal when the selected metric is non-zero');
assert.doesNotMatch(tracker,/tracker-intel-valuebar/,'Hot Zones no longer stretches proportional bars across the card');
assert.match(tracker,/tracker-intel-stat tracker-intel-selected/,'Hot Zones uses compact numeric signal cells');
assert.match(trackerCss,/\.tracker-intel-insight/,'Hot Zones insight treatment is styled');
assert.match(tracker,/trackerOverviewHtml\(losses,status,sourceUrl\)/,'Tracker pairs Hot Zones with recent Heavy Fighter losses');
assert.match(trackerCss,/\.tracker-overview-grid\{display:grid;grid-template-columns:/,'paired Tracker intel uses a restrained two-column layout');
assert.match(trackerCss,/\.fighter-loss-alarm-overlay/,'Heavy Fighter loss alarm has a dedicated visual overlay');
assert.match(tracker,/const ALERT_MAX_AGE_MS=60\*1000/,'Heavy Fighter alert window is capped at 60 seconds');
assert.match(tracker,/Date\.parse\(String\(row\?\.receivedAt\|\|''\)\)/,'Heavy Fighter alert freshness is based on JLR receive time');
assert.match(tracker,/filter\(isAlertFresh\)/,'polling cannot alarm on historical losses that merely look unseen');
assert.match(index,/id="scoutGlobalAlert"/,'Scout update requests are visible outside the Scout tab');
assert.doesNotMatch(app,/NO MICROPHONE REQUIRED/,'Scout omits redundant microphone copy');
assert.match(app,/id="scoutCharacterSelect"/,'Scout has a travel-toon selector');
assert.match(app,/id="scoutTargetList"/,'Scout exposes closest Field Tracker update targets');

assert.match(app,/appLedgerCoverageBadge/,'app ledger sync state is rendered as a badge');
assert.match(app,/myLedgerCoverageBadge/,'personal ledger sync state is rendered as a badge');
assert.match(app,/outside tracked fields/,'ledger diagnostics distinguish payout rows from field attribution');
assert.match(app,/fleetUptimeMeter/,'fleet target exposes the uptime assumption visually');

assert.equal(pkg.version,'2.10.10');
assert.ok(index.includes('/styles.css?v=2.10.10'),'main information-design CSS is cache-busted');
assert.ok(index.includes('/tracker.css?v=2.9.147-closest-init1'),'Tracker information-design CSS is cache-busted');
assert.ok(index.includes('/app.js?v=2.10.10'),'dashboard JS is cache-busted');
assert.ok(index.includes('/tracker.js?v=2.9.147-closest-init1'),'Tracker loader is cache-busted');
assert.match(trackerLoader,/tracker-core\.js\?v=2\.9\.147-closest-init1/,'Tracker core is cache-busted');

assert.match(styles,/\.app\.compact\{width:min\(1120px,calc\(100vw - 12px\)\);max-width:1120px\}/,'Compact app keeps a bounded design width');
assert.match(styles,/\.app\.expanded\{width:min\(1600px,calc\(100vw - 12px\)\);max-width:1600px\}/,'Expanded app keeps a bounded design width');
assert.match(styles,/grid-template-columns:repeat\(auto-fill,minmax\(250px,340px\)\)/,'Compact target cards are capped instead of stretched');
assert.match(styles,/\.fleet-miner-card,\.fleet-ore-card\{grid-column:1\/-1;width:100%;max-width:none/,'Miner comparison and ore mix get full-width review space');
assert.match(styles,/\.fleet-perf-list\.compact\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/,'Fleet Performance uses a compact two-column miner list');
assert.match(styles,/\.fleet-performance-summary-line/,'Fleet Performance uses a compact numeric actual-vs-target summary');
assert.match(index,/class="fleet-command-card fleet-miner-card"/,'Miner comparison lives inside the main Fleet Performance review');
assert.match(index,/ORE VALUE ANALYTICS/,'Ore market context is separated from fleet execution review');
assert.match(app,/class="fleet-perf-row compact"/,'per-miner performance no longer uses giant progress bars');
assert.doesNotMatch(app,/fleet-share-track/,'per-miner performance removes decorative share bars');
assert.match(index,/id="adamQuickToggle"/,'Ask Adam is available outside the Adam tab');
assert.match(index,/id="adamQuickPanel"/,'global Adam panel is present');
assert.match(index,/adam-quick-conversation/,'global Adam uses a conversation layout');
assert.match(styles,/app-tab\.adam-current/,'Adam shows a calm current state after an update clears');
assert.match(styles,/adam-nearest-mining/,'nearest mining system has a dedicated readable card');

assert.match(index,/id="toonLinkedCount"/,'Toons tab has a linked-character summary');
assert.match(app,/toon-state-'\+stateKey/,'Toons tab renders explicit per-character data states');
assert.match(styles,/v2\.9\.144-system-pass1/,'system-wide UI pass is styled');
assert.match(trackerCss,/tracker-hourly-badge/,'Tracker region selector shows its hourly refresh cadence');
assert.match(styles,/\.market-end-label/,'market chart uses direct end labels');
assert.match(app,/const ticks=3/,'market chart uses restrained grid density');
assert.doesNotMatch(app,/function areaPaths\(\)/,'market chart no longer shades the area between series');
assert.match(app,/class="fleet-latest-label"/,'live fleet chart labels the latest value directly');
assert.doesNotMatch(app,/class="fleet-activity-area"/,'live fleet chart no longer uses decorative area fill');
assert.match(app,/fleet-history-bar'\+\(i===bestIndex\?' best':'\'\)\+\(i===todayIndex\?' today':'\'\)/,'daily chart emphasizes best day and today');

assert.match(app,/doctrine-nyx-buyback/,'Doctrine includes the Nyx Buyback promo tile');
assert.match(app,/discord\.com\/channels\/1275408985171820585\/1465988346185515078/,'Nyx Buyback tile opens the configured Discord channel');
assert.match(styles,/Doctrine Nyx Buyback promo/,'Nyx Buyback promo is styled for the Doctrine side column');

console.log('Information design regression tests passed.');
