import assert from 'node:assert/strict';
import {initFieldAccess,redactFieldState,fieldRouteRequiresInit} from '../lib/init-field-access.mjs';
const user={id:'u',characterIds:['123']},cache=new Map();let clock=0,calls=0,member=true;
const options={cache,now:()=>clock,lookup:async()=>{calls++;return [{character_id:123,alliance_id:member?1900696668:42}]}};
assert.equal((await initFieldAccess(null,options)).allowed,false);
assert.equal((await initFieldAccess(user,options)).allowed,true);
member=false;clock=60001;
assert.equal((await initFieldAccess(user,options)).allowed,false,'membership removal takes effect when verification expires');
assert.equal(calls,2);
assert.equal((await initFieldAccess(user,{lookup:async()=>{throw Error('ESI unavailable')}})).allowed,false,'verification failure must deny');
assert.equal((await initFieldAccess(user,{lookup:async()=>[{character_id:999,alliance_id:1900696668}]})).allowed,false,'unlinked INIT character does not grant access');
assert.equal((await initFieldAccess({...user,characterIds:[]},options)).allowed,false,'unlinked account cannot reuse cached access');
const snapshot={app:{systemCount:1},source:{systems:[{system:'PRIVATE'}],ores:[{name:'Ore',systems:['PRIVATE']}],mapFields:[{system:'PRIVATE'}],mapFieldSnapshot:{source:'PRIVATE'},iceFields:[{system:'PRIVATE'}],a0Fields:[{system:'PRIVATE'}],gas:{wormholes:{reports:[{system:'PRIVATE'}]}}},fields:{PRIVATE:{}},scans:{PRIVATE:{}},trackerBrain:{nearest:'PRIVATE'},esi:{ledgerDebug:{system:'PRIVATE'}},market:{history:[{system:'PRIVATE'}]}};
assert.doesNotMatch(JSON.stringify(redactFieldState(snapshot,{allowed:false})),/PRIVATE/);
assert.match(JSON.stringify(redactFieldState(snapshot,{allowed:true})),/PRIVATE/);
assert.equal(snapshot.source.systems.length,1,'redaction never mutates shared state');
for(const p of ['/api/fields/X','/api/fields/X/notes','/api/scans/preview','/api/scout/location','/api/tracker/brain/ask'])assert.equal(fieldRouteRequiresInit(p),true);
assert.equal(fieldRouteRequiresInit('/api/tracker/heavy-fighters'),false);
console.log('INIT field authorization, expiry, failure and redaction tests passed.');
