import assert from 'node:assert/strict';
import {updateT2Ledger,currentT2Report} from '../lib/map-field-ledger.mjs';
import {T2_SITE_DATA} from '../lib/t2-site-data.mjs';
assert.equal(T2_SITE_DATA.Isogen.siteM3,3359899.2);
assert.equal(T2_SITE_DATA.Megacyte.ores.length,12);
T2_SITE_DATA.Test={siteM3:100,ores:[{name:'Test Ore',quantity:100}]};
const baseline='2026-10-04T17:00:00Z',fields=[{id:'one',system:'TEST',tier:2,mineral:'Test',scanReminderStartedAt:baseline}];
const reports={},snapshots={},systemCache={1:{name:'TEST'}},typeCache={1:{name:'Test Ore',volume:1}};
const input={fields,reports,snapshots,systemCache,typeCache};
const sample=(characterId,quantity,time)=>updateT2Ledger({...input,characterId,rows:[{date:'2026-10-04',solar_system_id:1,type_id:1,quantity}],sampleAt:time});
sample('a',10,baseline);sample('b',20,baseline);
sample('a',50,'2026-10-04T17:01:00Z');
sample('b',80,'2026-10-04T17:01:00Z');
assert.equal(reports.one.minedM3,100,'sum incremental mining from both linked toons');
assert.equal(reports.one.status,'cleared');
assert.equal(reports.one.timerEndsAt,'2026-10-04T21:01:00.000Z');
const end=reports.one.timerEndsAt;
sample('a',100,'2026-10-04T17:02:00Z');
assert.equal(reports.one.timerEndsAt,end,'later samples cannot restart the timer');
assert.equal(currentT2Report(fields[0],reports.one,Date.parse(end)).minedM3,0);
assert.equal(currentT2Report(fields[0],reports.one,Date.parse(end)).needsScan,true);
const snapshots2={},reports2={};
const shared={...input,snapshots:snapshots2,reports:reports2,fields:[...fields,{...fields[0],id:'two'}]};
const row={date:'2026-10-04',solar_system_id:1,type_id:1,quantity:0};
updateT2Ledger({...shared,characterId:'a',rows:[row],sampleAt:baseline});
updateT2Ledger({...shared,characterId:'a',rows:[{...row,quantity:100}],sampleAt:'2026-10-04T17:01:00Z'});
assert.equal(Object.keys(reports2).length,0,'shared ore must never be double-counted into both sites');
const early={...input,reports:{},snapshots:{}};
updateT2Ledger({...early,characterId:'a',rows:[{...row,quantity:10}],sampleAt:'2026-10-04T16:59:00Z'});
updateT2Ledger({...early,characterId:'a',rows:[{...row,quantity:110}],sampleAt:'2026-10-04T17:01:00Z'});
assert.equal(Object.keys(early.reports).length,0,'ignore daily totals that straddle the new-site boundary');
delete T2_SITE_DATA.Test;
console.log('Workbook T2 capacities, multiple-toon deltas, ambiguity and four-hour expiry passed.');
